### PR TITLE
Remove any explicit resource policies if not created

### LINKED ISSUE #238: Stack policy failing on conditional resources
When a resource contains both a stack policy rule and a condition that evaluates to false such as:

```ruby
dynamic!(:some_resource, :my_resource) do
  condition 'FalseCondition'
  policy do
    deny '*'
  end
end
```

Then when the stack policy callback triggers it will fail with an error indication that the policy is referencing a non-existent resource:

`ERROR: Miasma::Error::ApiError::RequestError: Bad Request - ValidationError: Error validating stack policy: Unknown logical id 'LogicalResourceId/MyResource' in statement {} - stack policies can only be applied to logical ids referenced in the template`

N.B. If the condition evaluates to `true` there is no error, since the resource was created

### PR DESCRIPTION
**Pull request by chrisroberts**
Fixes #238

### CODE REVIEW

File: lib/sfn/callback/stack_policy.rb [hunk 1]
```diff
@@ -74,19 +74,26 @@ def template(info)
       # @param p_stack [Miasma::Models::Orchestration::Stack]
       # @return [NilClass]
       def save_stack_policy(p_stack)
+        valid_logical_ids = p_stack.resources.reload.all.map(&:logical_id)
+        stack_policy = @policies.fetch(p_stack.id,
+          @policies.fetch(p_stack.data[:logical_id]),
+          @policies[p_stack.name]
+        ).to_smash
+        stack_policy[:statement].delete_if do |policy_item|
```
Comment (jimcroft) [inline lib/sfn/callback/stack_policy.rb]: This seems to cause an error updating stacks where we're using this callback but haven't explicitly set a stack policy.

```
[Sfn]: Applying stack policy to my-test-stack... error!
[ERROR]: Reason - undefined method `delete_if' for nil:NilClass
ERROR: NoMethodError: undefined method `delete_if' for nil:NilClass
```

Comment (chrisroberts) [inline lib/sfn/callback/stack_policy.rb]: :+1:
